### ISSUE TITLE
404 Not Found - http://localhost:9000/remixicon.woff2?t=1590207869815 

### ISSUE THREAD

**Issue by rajiv687** [single-spa/single-spa-playground#49] opened 2022-08-16 10:53 UTC
remixicon working perfectly fine on Angular application  howver when I integrate with single spa then getting 404 error:
Request URL: http://localhost:9000/remixicon.woff2?t=1590207869815
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:9000
Referrer Policy: strict-origin-when-cross-origin
![image](https://user-images.githubusercontent.com/17966722/184862596-83720558-3615-48e4-8d43-a7d6c5336f5a.png)

Kindly help to resolve this.

**Comment by filoxo** [comment] 2022-08-16 16:06
Duplicate of #48.

**Closed by filoxo** 2022-08-16 16:06 UTC
