### ISSUE TITLE
scripts js

### ISSUE THREAD

**Issue by NellyLinares-SB** [single-spa/single-spa-playground#39] opened 2020-12-07 14:51 UTC
## Data dump

Applications:
```json
{
  "framework": "angular",
  "name": "login",
  "pathPrefix": "/",
  "sharedDeps": [],
  "useNativeModules": false,
  "url": "http://localhost:4200/login"
}
```

Import map:
```json
{
  "imports": {
    "login": "http://localhost:4200/login"
  },
  "scopes": {}
}
```

**Comment by joeldenning** [comment] 2020-12-07 18:57
This is a duplicate of #38

**Closed by joeldenning** 2020-12-07 18:57 UTC
